const experienceData = [
  {
    id: 1,
    company: "Ready Meds Pharmacy",
    position: "Long-Term Care Pharmacist",
    duration: "June 2023 - Present",
    timeFrame: "2 yrs 6 mos",
    duties: [
      "Managed the development of a business intelligence dashboard, coordinating efforts between stakeholders and developers.",
      "Reviewed, assessed, and managed medication regimens for long-term care facility residents.",
      "Collaborated with healthcare teams to perform medication reconciliation during transitions of care, such as hospice.",
      "Facilitated communication between providers, facilities, and pharmacy staff by clarifying prescriptions, addressing urgent requests, and responding to pharmacist calls.",
      "Verified medication orders for completeness, accuracy, and appropriateness before dispensing.",
    ],
    img: "assets/experience-img/ready-meds-logo.jpg",
    imgAlt: "Ready Meds Pharmacy logo",
  },
  {
    id: 2,
    company: "Bartell Drugs",
    position: "Pharmacy Manager",
    duration: "Feb 2022 - Feb 2023",
    timeFrame: "1 yr 1 mo",
    duties: [
      "Directed daily operations, scheduling, and team performance for a high-volume retail pharmacy.",
      "Managed and facilitated the training and career development of ancillary staff.",
      "Dispensed medications while ensuring patient safety and overseeing quality assurance for all operations.",
      "Managed all areas of sales, customer service and key performance metrics.",
      "Organized clinical service events, including immunization clinics for Influenza and COVID-19 vaccinations.",
      "Ensured compliance with federal and state laws in all pharmacy related areas.",
    ],
    img: "assets/experience-img/bartell-drugs.jpeg",
    imgAlt: "Bartell Drugs logo",
  },
  {
    id: 3,
    company: "Bartell Drugs",
    position: "Staff Pharmacist",
    duration: "Oct 2020 - Feb 2022",
    timeFrame: "1 yrs 5 mo",
    duties: [
      "Processed prescriptions, billed insurance, verified and dispensed medications.",
      "Counseled and advised patients on their medication therapy.",
      "Offered advice on health issues, symptoms, and medications in response to patient inquiries.",
      "Provided pharmacological information in a community pharmacy setting at the request of health care professionals.",
    ],
    img: "assets/experience-img/bartell-drugs.jpeg",
    imgAlt: "Bartell Drugs logo",
  },
  {
    id: 4,
    company: "Bartell Drugs",
    position: "Pharmacy Intern",
    duration: "Dec 2017 - Oct 2020",
    timeFrame: "2 yrs 11 mos",
    duties: [
      "Assisted in the practice of pharmacy, under the supervision of the pharmacist and in accordance with state, federal, and company policy. ",
      "Supported pharmacy department with inventory management, including ordering, unpacking, checking and storing shipment of pharmaceuticals.",
      "Engaged patients by greeting them and offered assistance with products, services and medication counseling.",
      "Primary immunizer during cold and flu season.",
      "Handled calls that did not require personal attention from the pharmacist, including those to health care providers.",
    ],
    img: "assets/experience-img/bartell-drugs.jpeg",
    imgAlt: "Bartell Drugs logo",
  },
  {
    id: 5,
    company: "Washington State University, Department of Chemistry",
    position: "Organometallic Research Chemist",
    duration: "Jan 2013 - May 2016",
    timeFrame: "3 yrs 5 mos",
    duties: [
      "Research Topics: Selective extraction of Platinum group metals. Synthesis of  99mTc/Re radiopharmaceuticals for diagnostic imaging and therapy.",
      "Synthesized and characterized novel ligands for rhenium (Re) and technetium-99m (⁹⁹ᵐTc) radiopharmaceutical development.",
      "Synthesized and characterized novel multidentate soft-donor ligands (e.g. N, S donor frameworks) for complexation with platinum group metals (Rh).",
      "Characterized ligand and complex species using NMR, UV-Vis spectroscopy, and X-ray crystallography.",
      "Conducted solvent extraction studies to evaluate ligand performance, measuring metal distribution ratios via ICP-OES.",
    ],
    img: "assets/experience-img/wsu-logo.png",
    imgAlt: "Washington State University logo",
  },
];

export default experienceData;
